version: "3"
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.28
    volumes:
      - ./db-data:/var/lib/mysql
    command: --authentication_policy=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: test
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test-db
    ports:
      - "3306:3306"
volumes:
  db-data:
    driver: local
